development:
  adapter: mysql2
  database: auto_estimator_development
  username: root
  password:

test:
  adapter: mysql2
  database: auto_estimator_test
  username: root
  password:

production:
  adapter: mysql2
  database: auto_estimator_production
  username: root
  password:
